- 向量是一维的--只有长度而没有其他维度。
- 数组（array）可以看作是**带有多个下标的<font color=red>类型相同</font>的**元素的集合。
- 数组也可以看作是向量和矩阵的推广，**一维数组就是向量，二维数组就是矩阵**。

# 数组(array)的创建
 
   --函数array()，其句法是：
    	array(data = NA, dim = length(data), dimnames = NULL)

In [1]:
ta  <- array(1:24,c(4,3,2))   # 产生维数为(4,3,2)的3维数组，排列顺序是：行-列-面

In [2]:
class(ta)

[1] "array"

In [3]:
nrow(ta)   #返回行数

[1] 4

In [4]:
dim(ta)   #返回各维度值

[1] 4 3 2

In [5]:
ta[,,1]   #返回第一层，默认的排列顺序是：列-行-层

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [6]:
ta[,,2]    #返回第二层

[,1] [,2] [,3]
[1,] 13   17   21  
[2,] 14   18   22  
[3,] 15   19   23  
[4,] 16   20   24

In [7]:
ta  <- array(1:24,dim = c(4,3,2),dimnames = list(c("R1", "R2", "R3","R4"),c("C1", "C2", "C3"),c("L1", "L2")))
#指定维度值和行、列、层名
#在Rstudio展示更清楚

In [8]:
ta[,,1]

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

In [9]:
ta[,,2]

C1 C2 C3
R1 13 17 21
R2 14 18 22
R3 15 19 23
R4 16 20 24

In [10]:
array(1:3, c(2,4)) # recycle 1:3 --当数据不够用时

[,1] [,2] [,3] [,4]
[1,] 1    3    2    1   
[2,] 2    1    3    2

# 矩阵(matrix)的创建

- 矩阵将数据用行和列排列的长方形表格，它是二维的数组，其单元必须是<font color=red>相同的数据类型</font>。

- 矩阵通常**用列来表示不同的变量（属性、字段），用行表示各个对象（纪录，样例、观察）**。R语言生成矩阵的函数是matrix()，其句法是：

myymatrix <- matrix(vector, nrow=number_of_rows, ncol=number_of_columns,
                    byrow=logical_value, dimnames=list(              
                    char_vector_rownames, char_vector_colnames)) 
      
 其中，vector 项为必要的矩阵元素,nrow 为行数,ncol 为列数,注意 nrow 与 ncol 的乘积应为矩阵元素个数, dimnames 给定行和列的名称，byrow 项控制排列元素时是否按行进行,**默认byrow=FALSE，即按列顺序排列**。

In [11]:
(a <- matrix(1:12, nrow = 4, dimnames = list(c("R1", "R2", "R3", "R4"),c("C1", "C2", "C3"))))

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

In [12]:
class(a)

[1] "matrix" "array"

In [13]:
#该矩阵也可以用 array 函数来创建。下列二维数组与刚创建的矩阵完全相等：
(b <- array(1:12,dim = c(4, 3),dimnames = list(c("R1", "R2", "R3", "R4"),c("C1", "C2", "C3"))))

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

In [14]:
class(b)        ##二维array被认为是matrix

[1] "matrix" "array"

In [15]:
(c <- array(1:12,dim = c(2,3,2)))     #在Rstudio展示更清楚

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

In [16]:
class(c)

[1] "array"

In [17]:
identical(a, b)     #两个对象是否完全相等

[1] TRUE

## 用多个等长向量创建矩阵

用3个现有等长向量x，y，z，把它们分别作为列构建矩阵

In [18]:
x <- c(1, 3, 5)
y <- c(2, 4, 6)
z <- c(8, 10, 12)
(M <- cbind(x, y, z))

x y z 
[1,] 1 2  8
[2,] 3 4 10
[3,] 5 6 12

In [19]:
class(M)

[1] "matrix" "array"

# dim函数

--对于矩阵和数组，dim函数将返回其维度的整数值向量：

In [20]:
dim(c)

[1] 2 3 2

In [21]:
dim(a)

[1] 4 3

dim()可以用来将向量转化成数组或矩阵

In [22]:
zz <- 1:12
dim(zz)

NULL

In [23]:
dim(zz) <- c(2, 2, 3) # 将向量转成维度为（2,2,3）的数组
dim(zz)
#在Rstudio展示更清楚

[1] 2 2 3

可通过给 dim 函数分配一个新的维度来重塑矩阵或数组。不过请小心使用，因为它会删除原维度的名称：

In [24]:
a

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

In [25]:
dim(a) <- c(6, 2) 
a

[,1] [,2]
[1,] 1     7  
[2,] 2     8  
[3,] 3     9  
[4,] 4    10  
[5,] 5    11  
[6,] 6    12

# nrow 和 ncol 行数
--函数 nrow 和 ncol 将分别返回矩阵的行数和列数：

In [26]:
nrow(a)

[1] 6

In [27]:
ncol(a)

[1] 2

# length函数
--对于矩阵和数组，返回所有维度的乘积--所有元素的个数：

In [28]:
dim(ta)

[1] 4 3 2

In [29]:
length(ta)

[1] 24

In [30]:
dim(a)

[1] 6 2

In [31]:
length(a)

[1] 12

# 矩阵的加减法与数乘
--对应元素计算

In [32]:
A <- B <- matrix(1:12,nrow=3) #将生成的矩阵赋给B，同时又赋给A
A + B

[,1] [,2] [,3] [,4]
[1,] 2     8   14   20  
[2,] 4    10   16   22  
[3,] 6    12   18   24

In [33]:
3*A

[,1] [,2] [,3] [,4]
[1,] 3    12   21   30  
[2,] 6    15   24   33  
[3,] 9    18   27   36

In [34]:
A - A[1,]       #减去自身的第一行，怎么减的？

[,1] [,2] [,3] [,4]
[1,]  0   -6    0   6   
[2,] -2    4   -2   4   
[3,] -4    2    8   2

In [35]:
t(t(A)-A[1,])   # 各行减去第一行

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 1    1    1    1   
[3,] 2    2    2    2

# %*% 相乘
--矩阵的乘法，除了矩阵需要满足可以相乘的要求之外，在R中需要用运算符“%*%”来进行计算。

In [36]:
(A <- matrix(1:4, nrow = 2))

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [37]:
(B <- matrix(c(1,1,2,2), nrow = 2))

[,1] [,2]
[1,] 1    2   
[2,] 1    2

In [38]:
(result1 <- A * B)   #"*"是对应元素相乘

[,1] [,2]
[1,] 1    6   
[2,] 2    8

In [39]:
(result2 <- A %*% B)   #"%*%"是矩阵相乘

[,1] [,2]
[1,] 4     8  
[2,] 6    12

# 对各行、列运算

In [40]:
rowSums(A)  #求各行和

[1] 4 6

In [41]:
colSums(A) #求各列和

[1] 3 7

In [42]:
rowMeans(A) #求各行均值

[1] 2 3

In [43]:
colMeans(A)  #求各列均值

[1] 1.5 3.5

# apply函数
--apply函数可以矩阵的行、列进行各种更为复杂、灵活地计算，其用法为：
apply(X, MARGIN, FUN, ...) 

其中，X表示需要处理的数据，MARGIN表示函数的作用范围，1为对行运算，2为对列运算。FUN为需要运用的函数。

In [44]:
A <- matrix(1:4,2,2)
A

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [45]:
apply(A, 2, sum) #矩阵的列求和

[1] 3 7

In [46]:
(s<-apply(A, 1, sum)) #矩阵的行求和--还是写成行的形式，实际上返回的是向量--无所谓行、列
class(s)

[1] 4 6

[1] "integer"

In [47]:
apply(A, 2, mean) #矩阵的列求均值

[1] 1.5 3.5

In [48]:
apply(A, 2, var) #矩阵的列求方差

[1] 0.5 0.5

In [49]:
apply(A, 2, sd) #矩阵的列求标准差

[1] 0.7071068 0.7071068

# diag函数
--对角元素

In [50]:
(A <- matrix(1:16,nrow=4)) 

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [51]:
diag(A) #取一个方阵的对角元素

[1]  1  6 11 16

In [52]:
diag(diag(A)) #产生以某向量的元素为对角元的对角矩阵

[,1] [,2] [,3] [,4]
[1,] 1    0     0    0  
[2,] 0    6     0    0  
[3,] 0    0    11    0  
[4,] 0    0     0   16

In [53]:
diag(3) #生成一个对应维数的单位阵

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

# solve函数
--方阵求逆

In [54]:
set.seed(0)
(A <- matrix(rnorm(16),4,4)) #rnorm()是生成16个标准正态分布随机数

[,1]       [,2]       [,3]         [,4]      
[1,]  1.2629543  0.4146414 -0.005767173 -1.1476570
[2,] -0.3262334 -1.5399500  2.404653389 -0.2894616
[3,]  1.3297993 -0.9285670  0.763593461 -0.2992151
[4,]  1.2724293 -0.2947204 -0.799009249 -0.4115108

In [55]:
(R_A <- solve(A))

[,1]        [,2]       [,3]      [,4]      
[1,]  0.05541852 -0.5504911 1.1230126 -0.5838917
[2,]  0.48142273 -0.6728353 0.6887668 -1.3701648
[3,]  0.23906964 -0.1917792 0.7716981 -1.0929505
[4,] -0.63762072 -0.8479228 1.4808033 -1.1320912

In [56]:
A %*% R_A

[,1]          [,2]         [,3]          [,4]         
[1,]  1.000000e+00 1.110223e-16 -2.220446e-16 -2.220446e-16
[2,] -8.326673e-17 1.000000e+00  1.665335e-16  4.996004e-16
[3,] -2.775558e-17 0.000000e+00  1.000000e+00  5.551115e-17
[4,] -5.551115e-17 0.000000e+00 -1.110223e-16  1.000000e+00

In [57]:
R_A %*% A

[,1]          [,2]          [,3]          [,4]         
[1,]  1.000000e+00  8.326673e-17  0.000000e+00  5.551115e-17
[2,] -2.220446e-16  1.000000e+00  0.000000e+00  1.110223e-16
[3,]  0.000000e+00 -5.551115e-17  1.000000e+00 -5.551115e-17
[4,]  4.440892e-16  5.551115e-17 -2.220446e-16  1.000000e+00

# rbind和cbind函数
--对矩阵按照行和列进行合并

In [58]:
B <- matrix(c(1, 1, 1, 1), 2, 2) # 生成2×2的矩阵
rbind(B, B) # 将B和B矩阵按行合并

[,1] [,2]
[1,] 1    1   
[2,] 1    1   
[3,] 1    1   
[4,] 1    1

In [59]:
cbind(B,B) #将B和B矩阵按列合并

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 1    1    1    1

# t函数
--矩阵转置

In [60]:
(A <- matrix(1:16,nrow=4))

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [61]:
t(A)

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

# 矩阵索引
- 对于得到的矩阵，可以使用A[i,j]得到A矩阵第i行第j列的元素
- **A[i,]**和**A[,j]**分别表示返回**第i行和第j列的所有元素**。
- 可以使用**A[i:k,j:l]**的形式来获得**多行多列的子矩阵**。

In [7]:
(A <- matrix(1:12, 3, 4))

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [8]:
A[2,3] #返回矩阵第2行第3列元素

[1] 8

In [9]:
A[2,] #返回矩阵第2行所有元素

[1]  2  5  8 11

In [10]:
A[,3] #返回矩阵第3列所有元素

[1] 7 8 9

In [11]:
class(A[,3])       #取出的是向量

[1] "integer"

In [12]:
a <- A[1:3, c(2, 4)] # 返回矩阵第1-3行，第2、4列的元素
a

[,1] [,2]
[1,] 4    10  
[2,] 5    11  
[3,] 6    12

In [13]:
class(a)

[1] "matrix" "array"

In [14]:
(a <- matrix(1:12, nrow = 4, dimnames = list(c("R1", "R2", "R3", "R4"),c("C1", "C2", "C3"))))

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

对于行列命名的矩阵，可以通过行列名访问

In [15]:
a["R1",]    #获取第一行

C1 C2 C3 
 1  5  9

In [17]:
a[,"C1"]    #获取第一列

R1 R2 R3 R4 
 1  2  3  4

In [20]:
a["R1","C1"]    #获取第一行的第一列

[1] 1

# 数组索引

- 索引数组与索引向量类似，只是现在要索引的维度多于一个。和之前一样，用方括号来表示索引
- 仍有四种指定索引的方法（**正整数、负整数、逻辑值和元素的名称**）。在不同的维度上用不同的方式指定索引下标完全没问题。每个维度的下标用逗号分隔

In [22]:
#Rstudio演示
three_d_array  <- array(1:24,dim = c(4,3,2),dimnames = list(c("R1", "R2", "R3","R4"),c("C1", "C2", "C3"),c("L1", "L2")))

In [70]:
three_d_array[,,1]    #第1“面”上的元素

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

In [71]:
three_d_array[,,2]    #第2“面”上的元素

C1 C2 C3
R1 13 17 21
R2 14 18 22
R3 15 19 23
R4 16 20 24

In [72]:
three_d_array[1,,]    #第1“行”上的元素

L1 L2
C1 1  13
C2 5  17
C3 9  21

In [73]:
three_d_array[,1,]    #第1“列”上的元素

L1 L2
R1 1  13
R2 2  14
R3 3  15
R4 4  16

In [74]:
three_d_array[,,-1] #去掉第1面

C1 C2 C3
R1 13 17 21
R2 14 18 22
R3 15 19 23
R4 16 20 24

In [75]:
three_d_array[,-1,] #去掉第1列

, , L1

   C2 C3
R1  5  9
R2  6 10
R3  7 11
R4  8 12

, , L2

   C2 C3
R1 17 21
R2 18 22
R3 19 23
R4 20 24

In [76]:
three_d_array[-1,,] #去掉第1行

, , L1

   C1 C2 C3
R2  2  6 10
R3  3  7 11
R4  4  8 12

, , L2

   C1 C2 C3
R2 14 18 22
R3 15 19 23
R4 16 20 24

对于行、列、层命名的矩阵，可以通过行、列、层名访问

In [23]:
three_d_array[,,"L1"]    #第1“面”上的元素

C1 C2 C3
R1 1  5   9
R2 2  6  10
R3 3  7  11
R4 4  8  12

In [24]:
three_d_array["R1",,]    #第1“行”上的元素

L1 L2
C1 1  13
C2 5  17
C3 9  21

In [25]:
three_d_array[,"C1",]    #第1“列”上的元素

L1 L2
R1 1  13
R2 2  14
R3 3  15
R4 4  16

In [26]:
three_d_array["R1","C1",]    #第1“行”.第1“列”上的元素

L1 L2 
 1 13